### ISSUE TITLE
Kurosearch not loading at all on every browser on mobile and also not loading on opera gx on pc while it loads fine on chrome and edge on pc,

### ISSUE THREAD

**Issue by RacerTheDestroyerZX** [kurozenzen/kurosearch#17]
Suddenly kurosearch became unusable cause it just infinitely loads and if i reload the page none of the buttons fuction that are used for searching,while images also do no load,thìs seems to happen on both mobile and pc,but from what i know it only happends on opera gx on pc for now,while it happends in every browser on mobile

**Comment by kurozenzen** [comment]
Handled on discord
