### ISSUE TITLE
[feature request] grid view

### ISSUE THREAD

**Issue by dxcvvxd** [kurozenzen/kurosearch#7]
title is self-explanatory.
could you add grid view and perhaps make the pictures a little smaller so its easier to see more at a time? i think that would be pretty nice considering only one image/video at a time can be displayed on screen now.

**Comment by kurozenzen** [comment]
Hey. sorry for the slow response. I got the same feature request on discord a while ago. I am more active there. I want to add it but unfortunately it will require me to rethink some of the mechanisms of the layout.

So don't expect it too soon.

If you don't mind me asking, are you using it on mobile or desktop?

**Comment by kurozenzen** [comment]
Is implemented now.

**Comment by dxcvvxd** [comment]
thanks :p
so first of all, im using it on both mobile and dekstop but my mobile looks like desktop so yeah basically desktop lol.
and also, sorry, i didnt notice you had a discord.
